apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
  namespace: stag
spec:
  selector:
    app: jenkins-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
